import type { RequestHandler } from 'express';
import { AppError } from '../auth/auth.errors.js';
import { labService } from './lab.service.js';
import { emptyBodySchema, feedbackSearchSchema, productSearchSchema, profileAccessSchema, slugSchema, submissionSchema, trainingLoginSchema } from './lab.validators.js';

function parseSlug(value: unknown) { const result = slugSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Invalid lab slug.'); return result.data; }
function parseEmptyBody(value: unknown) { if (!emptyBodySchema.safeParse(value).success) throw new AppError(400, 'VALIDATION_ERROR', 'This request does not accept body fields.'); }
function parseSubmission(value: unknown) { const result = submissionSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'A submission object is required.'); return result.data.submission; }
function parseProductSearch(value: unknown) { const result = productSearchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Search must be a string with at most 120 characters.'); return result.data.search; }
function parseFeedbackSearch(value: unknown) { const result = feedbackSearchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Feedback must be a string with at most 500 characters.'); return result.data.feedback; }
function parseProfileAccess(value: unknown) { const result = profileAccessSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Profile ID must be a valid training profile identifier.'); return result.data.id; }
function parseTrainingLogin(value: unknown) { const result = trainingLoginSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Training username and password must be valid strings.'); return result.data; }

export const listLabs: RequestHandler = async (_request, response, next) => { try { response.status(200).json({ data: { labs: await labService.listPublishedLabs() } }); } catch (error) { next(error); } };
export const getLab: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { lab: await labService.getPublishedLab(parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const getProgress: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { progress: await labService.getProgressForUser(request.auth!.id) } }); } catch (error) { next(error); } };
export const getLabProgress: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { progress: await labService.getProgressForLab(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const startLab: RequestHandler = async (request, response, next) => { try { parseEmptyBody(request.body); response.status(200).json({ data: await labService.startLab(request.auth!.id, parseSlug(request.params.slug)) }); } catch (error) { next(error); } };
export const getSession: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { session: await labService.getSession(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const submitLab: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.submit(request.auth!.id, parseSlug(request.params.slug), parseSubmission(request.body)) }); } catch (error) { next(error); } };
export const completeLab: RequestHandler = async (request, response, next) => { try { parseEmptyBody(request.body); response.status(200).json({ data: { progress: await labService.completeLab(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const searchProductTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.searchProductTarget(request.auth!.id, parseSlug(request.params.slug), parseProductSearch(request.query)) }); } catch (error) { next(error); } };
export const searchFeedbackTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.searchFeedbackTarget(request.auth!.id, parseSlug(request.params.slug), parseFeedbackSearch(request.query)) }); } catch (error) { next(error); } };
export const getProfileTarget: RequestHandler = async (request, response, next) => { try { const target = await labService.getProfileTarget(request.auth!.id, parseSlug(request.params.slug), parseProfileAccess(request.query)); if (!target) throw new AppError(404, 'PROFILE_NOT_FOUND', 'Training profile not found.'); response.status(200).json({ data: target }); } catch (error) { next(error); } };
export const loginTrainingTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.loginTrainingTarget(request.auth!.id, parseSlug(request.params.slug), parseTrainingLogin(request.body)) }); } catch (error) { next(error); } };
