import type { RequestHandler } from 'express';
import { AppError } from '../auth/auth.errors.js';
import { labService } from './lab.service.js';
import { hasValidCsrfToken } from '../../middleware/csrf.js';
import { csrfSettingsSchema, directorySearchSchema, emptyBodySchema, feedbackSearchSchema, mockFetchSchema, productSearchSchema, profileAccessSchema, slugSchema, submissionSchema, trainingLoginSchema, trainingReportSchema, uploadHeadersSchema } from './lab.validators.js';
import { parseMockTargetPath } from './isolated-targets/mock-fetch.target.js';
import { isSupportedDirectoryQuery } from './isolated-targets/user-directory.target.js';

function parseSlug(value: unknown) { const result = slugSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Invalid lab slug.'); return result.data; }
function parseEmptyBody(value: unknown) { if (!emptyBodySchema.safeParse(value).success) throw new AppError(400, 'VALIDATION_ERROR', 'This request does not accept body fields.'); }
function parseSubmission(value: unknown) { const result = submissionSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'A submission object is required.'); return result.data.submission; }
function parseProductSearch(value: unknown) { const result = productSearchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Search must be a string with at most 120 characters.'); return result.data.search; }
function parseFeedbackSearch(value: unknown) { const result = feedbackSearchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Feedback must be a string with at most 500 characters.'); return result.data.feedback; }
function parseProfileAccess(value: unknown) { const result = profileAccessSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Profile ID must be a valid training profile identifier.'); return result.data.id; }
function parseTrainingLogin(value: unknown) { const result = trainingLoginSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Training username and password must be valid strings.'); return result.data; }
function parseTrainingReport(value: unknown) { const result = trainingReportSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Section must be a valid training workspace section.'); return result.data.section; }
function parseMockFetch(value: unknown) { const result = mockFetchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'A mock target path is required.'); const path = parseMockTargetPath(result.data.url); if (!path) throw new AppError(400, 'VALIDATION_ERROR', 'Only predefined in-memory mock paths are allowed.'); return path; }
function parseDirectorySearch(value: unknown) { const result = directorySearchSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Query must be a string between 1 and 120 characters.'); if (!isSupportedDirectoryQuery(result.data.q)) throw new AppError(400, 'VALIDATION_ERROR', 'This mock target accepts only controlled lookup input.'); return result.data.q; }
function parseUploadHeaders(value: unknown) { const result = uploadHeadersSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Upload filename and MIME type headers are required.'); return result.data; }
function parseCsrfSettings(value: unknown) { const result = csrfSettingsSchema.safeParse(value); if (!result.success) throw new AppError(400, 'VALIDATION_ERROR', 'Notification preference must be a boolean value.'); return result.data; }

export const listLabs: RequestHandler = async (_request, response, next) => { try { response.status(200).json({ data: { labs: await labService.listPublishedLabs() } }); } catch (error) { next(error); } };
export const getLab: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { lab: await labService.getPublishedLab(parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const getProgress: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { progress: await labService.getProgressForUser(request.auth!.id) } }); } catch (error) { next(error); } };
export const getLabProgress: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { progress: await labService.getProgressForLab(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const startLab: RequestHandler = async (request, response, next) => { try { parseEmptyBody(request.body); response.status(200).json({ data: await labService.startLab(request.auth!.id, parseSlug(request.params.slug)) }); } catch (error) { next(error); } };
export const getSession: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: { session: await labService.getSession(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const submitLab: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.submit(request.auth!.id, parseSlug(request.params.slug), parseSubmission(request.body)) }); } catch (error) { next(error); } };
export const completeLab: RequestHandler = async (request, response, next) => { try { parseEmptyBody(request.body); response.status(200).json({ data: { progress: await labService.completeLab(request.auth!.id, parseSlug(request.params.slug)) } }); } catch (error) { next(error); } };
export const searchProductTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.searchProductTarget(request.auth!.id, parseSlug(request.params.slug), parseProductSearch(request.query)) }); } catch (error) { next(error); } };
export const searchFeedbackTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.searchFeedbackTarget(request.auth!.id, parseSlug(request.params.slug), parseFeedbackSearch(request.query)) }); } catch (error) { next(error); } };
export const getProfileTarget: RequestHandler = async (request, response, next) => { try { const target = await labService.getProfileTarget(request.auth!.id, parseSlug(request.params.slug), parseProfileAccess(request.query)); if (!target) throw new AppError(404, 'PROFILE_NOT_FOUND', 'Training profile not found.'); response.status(200).json({ data: target }); } catch (error) { next(error); } };
export const loginTrainingTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.loginTrainingTarget(request.auth!.id, parseSlug(request.params.slug), parseTrainingLogin(request.body)) }); } catch (error) { next(error); } };
export const getTrainingReportTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.getTrainingReportTarget(request.auth!.id, parseSlug(request.params.slug), parseTrainingReport(request.query)) }); } catch (error) { next(error); } };
export const fetchMockTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.fetchMockTarget(request.auth!.id, parseSlug(request.params.slug), parseMockFetch(request.query)) }); } catch (error) { next(error); } };
export const searchDirectoryTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.searchDirectoryTarget(request.auth!.id, parseSlug(request.params.slug), parseDirectorySearch(request.query)) }); } catch (error) { next(error); } };
export const uploadProfileImageTarget: RequestHandler = async (request, response, next) => { try { const headers = parseUploadHeaders({ filename: request.header('X-Upload-Filename'), mimeType: request.header('X-Upload-Mime-Type') }); const content = Buffer.isBuffer(request.body) ? request.body : Buffer.alloc(0); response.status(200).json({ data: await labService.uploadProfileImageTarget(request.auth!.id, parseSlug(request.params.slug), { ...headers, content }) }); } catch (error) { next(error); } };
export const getProfileUploadTarget: RequestHandler = async (request, response, next) => { try { const filename = typeof request.params.filename === 'string' ? request.params.filename : ''; const content = await labService.getProfileUploadTarget(request.auth!.id, parseSlug(request.params.slug), filename); if (!content) throw new AppError(404, 'FILE_NOT_FOUND', 'Training upload not found.'); response.set({ 'Content-Type': 'application/octet-stream', 'Content-Disposition': 'attachment; filename="training-upload.bin"', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-store' }).status(200).send(content); } catch (error) { next(error); } };
export const getCsrfSettingsTarget: RequestHandler = async (request, response, next) => { try { response.status(200).json({ data: await labService.getCsrfSettingsTarget(request.auth!.id, parseSlug(request.params.slug)) }); } catch (error) { next(error); } };
export const updateCsrfSettingsTarget: RequestHandler = async (request, response, next) => { try { const settings = parseCsrfSettings(request.body); response.status(200).json({ data: await labService.updateCsrfSettingsTarget(request.auth!.id, parseSlug(request.params.slug), settings.notificationsEnabled, hasValidCsrfToken(request)) }); } catch (error) { next(error); } };
